(function(root,factory){
  'use strict';
  let feedback=root.WrongAnswerFeedback;
  if(typeof module==='object'&&module.exports){try{feedback=require('./feedback');}catch(_){}}
  const api=factory(feedback);
  if(typeof module==='object'&&module.exports) module.exports=api;
  root.ExplanationModel=api;
})(typeof window!=='undefined'?window:globalThis,function(Feedback){
  'use strict';
  const SCHEMA_VERSION=1;
  const REQUIRED_SECTIONS=Object.freeze(['sources','summary','calculation','transfer','checks','mistakes']);
  const labels={date:'日付',description:'摘要',quantity:'数量',unitPrice:'単価',amount:'金額',debit:'借方',credit:'貸方',balance:'残高',asset:'固定資産',acquisitionDate:'取得日',acquisitionCost:'取得原価',life:'耐用年数',months:'使用月数',openingAccumulated:'期首減価償却累計額',currentDepreciation:'当期減価償却費',closingAccumulated:'期末減価償却累計額',closingBookValue:'期末帳簿価額'};
  const obj=v=>!!v&&typeof v==='object'&&!Array.isArray(v);
  const arr=v=>Array.isArray(v)?v:(v==null?[]:[v]);
  const clone=v=>v==null?v:JSON.parse(JSON.stringify(v));
  const num=v=>typeof v==='number'&&Number.isFinite(v)?v.toLocaleString('ja-JP'):String(v??'');
  const shown=v=>v!=null&&v!==''&&v!=='入力'&&v!=='—';
  const rowName=(q,r,i)=>String(['date','asset','account','item','description'].map(k=>r?.[k]).find(shown)||`${q.category||'表'} ${i+1}行目`);
  function locations(q){const m=new Map();let n=0;if(!q?.table?.rows||!Array.isArray(q.table.inputCells))return m;q.table.rows.forEach((r,ri)=>Object.entries(r).forEach(([c,v])=>{if(v==='入力'){const id=q.table.inputCells[n++];if(id)m.set(id,{ri,c,r});}}));return m;}
  const cellLabel=(q,id,p)=>q?.table?.inputMetadata?.[id]?.label||(!p?id:`${rowName(q,p.r,p.ri)}／${labels[p.c]||p.c}`);
  function sourceValues(m){if(!obj(m))return[{label:'内容',value:String(m??'')}];return Object.entries(m).filter(([k,v])=>!['資料','title','name','type','document'].includes(k)&&shown(v)).map(([k,v])=>({label:String(k),value:num(v)}));}
  function sources(q){const ms=arr(q.materials).filter(v=>v!=null);if(ms.length)return ms.map((m,i)=>({kind:'material',title:String(m?.['資料']||m?.title||m?.name||m?.type||m?.document||`資料${i+1}`),focus:'資料の項目と数値を確認',values:sourceValues(m),evidenceRef:`materials[${i}]`}));if(q.table?.rows?.length)return[{kind:'table',title:q.category||'問題の表',focus:'行・列・入力欄の位置と、すでに記載されている数値を確認',values:q.table.rows.map((r,i)=>({label:rowName(q,r,i),value:Object.entries(r).filter(([,v])=>shown(v)).map(([k,v])=>`${labels[k]||k}:${num(v)}`).join(' / ')})),evidenceRef:'table.rows'}];return[{kind:'prompt',title:'問題文',focus:'取引条件・日付・金額・指定された処理を確認',values:[{label:'問題',value:String(q.question||'')}],evidenceRef:'question'}];}
  function valueAt(q,cells,locs,ri,c){const raw=q.table.rows[ri]?.[c];if(typeof raw==='number'&&Number.isFinite(raw))return raw;if(raw!=='入力')return null;for(const[id,p]of locs)if(p.ri===ri&&p.c===c){const v=cells[id];return typeof v==='number'&&Number.isFinite(v)?v:null;}return null;}
  function calculations(q){if(q.type==='journal')return [...(q.answer?.debit||[]),...(q.answer?.credit||[])].map(r=>({label:r.account,expression:null,result:r.amount,operands:[],evidenceRefs:['answer']}));const cells=q.answer?.cells||{},locs=locations(q);return Object.entries(cells).map(([id,expected])=>{const p=locs.get(id);if(typeof expected==='number'&&p?.c==='balance'&&p.ri>0){const prev=valueAt(q,cells,locs,p.ri-1,'balance'),d=valueAt(q,cells,locs,p.ri,'debit')||0,c=valueAt(q,cells,locs,p.ri,'credit')||0;if(Number.isFinite(prev)&&prev+d-c===expected){const parts=[num(prev)];if(d)parts.push('+',num(d));if(c)parts.push('−',num(c));parts.push('=',num(expected));return{label:cellLabel(q,id,p),expression:parts.join(' '),result:expected,operands:[{label:'直前残高',value:prev},...(d?[{label:'借方記入（増加）',value:d}]:[]),...(c?[{label:'貸方記入（減少）',value:c}]:[])],evidenceRefs:[`table.rows[${p.ri-1}]`,`table.rows[${p.ri}]`,`answer.cells.${id}`]};}}if(typeof expected==='number'&&p?.c==='amount'){const qty=valueAt(q,cells,locs,p.ri,'quantity'),unit=valueAt(q,cells,locs,p.ri,'unitPrice');if(Number.isFinite(qty)&&Number.isFinite(unit)&&qty*unit===expected)return{label:cellLabel(q,id,p),expression:`${num(qty)} × ${num(unit)} = ${num(expected)}`,result:expected,operands:[{label:'数量',value:qty},{label:'単価',value:unit}],evidenceRefs:[`table.rows[${p.ri}]`,`answer.cells.${id}`]};}return{label:cellLabel(q,id,p),expression:null,result:expected,operands:[],evidenceRefs:[p?`table.rows[${p.ri}]`:'answer.cells',`answer.cells.${id}`]};});}
  function transfer(q){if(q.type==='journal')return['debit','credit'].flatMap(side=>(q.answer?.[side]||[]).map(r=>({from:'問題文・証憑',decision:r.account,to:side==='debit'?'借方':'貸方',debitCredit:side,value:r.amount,evidenceRefs:[`answer.${side}`]})));const locs=locations(q);return Object.entries(q.answer?.cells||{}).map(([id,value])=>{const p=locs.get(id);return{from:p?rowName(q,p.r,p.ri):(q.category||'問題資料'),decision:cellLabel(q,id,p),to:labels[p?.c]||p?.c||id,debitCredit:null,value,evidenceRefs:[p?`table.rows[${p.ri}]`:'table',`answer.cells.${id}`]};});}
  function checks(q){if(q.type==='journal'){const d=(q.answer?.debit||[]).reduce((s,r)=>s+(Number(r.amount)||0),0),c=(q.answer?.credit||[]).reduce((s,r)=>s+(Number(r.amount)||0),0);return[{label:'借方合計と貸方合計が一致',expected:d===c?`${num(d)} = ${num(c)}`:'不一致',evidenceRefs:['answer.debit','answer.credit']}];}const locs=locations(q),out=Object.entries(q.answer?.cells||{}).map(([id,v])=>({label:`${cellLabel(q,id,locs.get(id))}を正答値と照合`,expected:num(v),evidenceRefs:[`answer.cells.${id}`]}));if(q.type==='ledger')out.unshift({label:'上から順に残高または帳簿値を更新',expected:'各行の結果を次の行の計算へ引き継ぐ',evidenceRefs:['table.rows']});return out;}
  function diagnostics(q,a,s,o){return Array.isArray(o?.diagnostics)?o.diagnostics:(Feedback?.diagnoseWrongAnswer?Feedback.diagnoseWrongAnswer(q,a||{},s||{correct:false}):[]);}
  function generated(q,a,s,o){const ds=diagnostics(q,a,s,o);return{schemaVersion:SCHEMA_VERSION,source:'generated',sources:sources(q),summary:String(q.question||'').trim()?[{text:String(q.question).trim(),evidenceRef:'question'}]:[],calculation:calculations(q),transfer:transfer(q),checks:checks(q),mistakes:ds.slice(0,3).map(x=>({title:x.title||'今回の間違い',reason:x.reason||'',correction:x.nextRule||x.thinking||'',diagnosticKind:x.kind||'general',cause:x.cause||x.kind||'general'})),fallback:{authoredExplanation:String(q.explanation||''),diagnostics:clone(ds)}};}
  function merge(g,a){if(!obj(a))return g;const m={...g,source:'authored'};REQUIRED_SECTIONS.forEach(k=>{if(Array.isArray(a[k]))m[k]=clone(a[k]);});if(obj(a.fallback))m.fallback={...g.fallback,...clone(a.fallback)};return m;}
  function validate(m){const e=[];if(!obj(m))return{valid:false,errors:['model must be an object']};if(m.schemaVersion!==SCHEMA_VERSION)e.push(`schemaVersion must be ${SCHEMA_VERSION}`);REQUIRED_SECTIONS.forEach(k=>{if(!Array.isArray(m[k]))e.push(`${k} must be an array`);});if(!obj(m.fallback))e.push('fallback must be an object');if(m.fallback&&typeof m.fallback.authoredExplanation!=='string')e.push('fallback.authoredExplanation must be a string');if(m.fallback&&!Array.isArray(m.fallback.diagnostics))e.push('fallback.diagnostics must be an array');return{valid:e.length===0,errors:e};}
  function build(q,a={},s={correct:false},o={}){if(!obj(q))throw new TypeError('question must be an object');const m=merge(generated(q,a,s,o),q.explanationModel),v=validate(m);if(!v.valid)throw new Error(`invalid explanation model: ${v.errors.join('; ')}`);return m;}
  return Object.freeze({SCHEMA_VERSION,REQUIRED_SECTIONS,build,validate});
});
