'use strict';
const assert=require('assert'),fs=require('fs'),vm=require('vm');
const view=fs.readFileSync('js/view.js','utf8'),css=fs.readFileSync('css/style.css','utf8'),html=fs.readFileSync('index.html','utf8'),worker=fs.readFileSync('service-worker.js','utf8');
const sandbox={window:{}};vm.runInNewContext(fs.readFileSync('data/questions.js','utf8'),sandbox,{filename:'data/questions.js'});
const q=sandbox.window.QuestionData;
assert(q.L034.explanationModel&&q.L041.explanationModel,'最終runtimeのL034/L041にstructured explanationを持たせる');
assert.strictEqual(q.L034.category,'仕訳帳');
assert.strictEqual(q.L041.category,'仕訳帳');
assert(String(q.L034.explanation).startsWith('仕訳帳は日付、摘要欄の勘定科目、元丁、借方・貸方金額を日付順に記入します。'),'L034のauthored先頭説明を保持する');
assert(String(q.L041.explanation).startsWith('仕訳帳は日付、摘要欄の勘定科目、元丁、借方・貸方金額を日付順に記入します。'),'L041のauthored先頭説明を保持する');
for(const label of ['まずここを確認','どういう取引か考える','必要な金額を出す','最後に確認','間違えやすいところ'])assert(view.includes(label),`教材見出し「${label}」を実画面rendererに持つ`);
assert(view.includes("format === 'fixed-asset-ledger'"),'固定資産台帳専用の教育プロファイルを持つ');
assert(view.includes("format === 'bookkeeping-notes-receivable'"),'受取手形記入帳専用の教育プロファイルを持つ');
assert(view.includes("format === 'bookkeeping-inventory-ledger'"),'商品有高帳専用の教育プロファイルを持つ');
assert(view.includes("format === 'bookkeeping-voucher-entry'"),'伝票専用の教育プロファイルを持つ');
assert(view.includes("...(hasMeaningfulCalculation ? [['必要な金額を出す','calculation']] : [])"),'算術計算がない問題では計算セクションを表示しない');
assert(view.includes('score.correct || !question.explanationModel'),'構造化解説は誤答かつ対象問題だけに限定する');
assert(view.includes('appendAuthoredExplanation(question, container, authoredOnly = false)'),'authored proseだけを分離表示できる');
assert(view.includes("const markers = ['【この問題への当てはめ】','【使用する資料】']"),'旧生成長文をstructured PoCへ重複表示しない');
assert(view.includes('renderLearningTakeaway(question, container)'),'構造化解説の最後は学習持ち帰りカードにする');
assert(view.includes('この問題で覚えること'),'持ち帰りカードの見出しを持つ');
assert(view.includes('元丁には総勘定元帳の転記先を示す番号'),'仕訳帳の元丁の意味を一般化して説明する');
assert(view.includes('証憑に金額が示されている場合は、その金額をそのまま記入'),'直接記載額と計算問題を見分ける原則を持つ');
assert(!view.includes('this.appendAuthoredExplanation(question, container, true)'),'構造化解説では旧authored解説を重複表示しない');
assert(/\.explanation-formula strong\s*\{[^}]*overflow-wrap:\s*anywhere/s.test(css),'計算ブロックをiPhoneでクリップしない');
const feedbackIndex=html.indexOf('js/feedback.js?v=20260924-111'),modelIndex=html.indexOf('js/explanation-model.js?v=20260924-111'),viewIndex=html.indexOf('js/view.js?v=20260924-111');
assert(feedbackIndex>=0&&feedbackIndex<modelIndex&&modelIndex<viewIndex,'feedback→explanation model→viewの順に読み込む');
assert(worker.includes("'./js/explanation-model.js'"),'PWAキャッシュへexplanation modelを含める');
console.log('explanation integration tests: PASS');
