'use strict';
const assert=require('assert'),fs=require('fs'),vm=require('vm');
const view=fs.readFileSync('js/view.js','utf8'),css=fs.readFileSync('css/style.css','utf8'),html=fs.readFileSync('index.html','utf8'),worker=fs.readFileSync('service-worker.js','utf8');
const sandbox={window:{}};vm.runInNewContext(fs.readFileSync('data/questions.js','utf8'),sandbox,{filename:'data/questions.js'});
const q=sandbox.window.QuestionData;
assert(q.L034.explanationModel&&q.L041.explanationModel,'最終runtimeのL034/L041にstructured explanationを持たせる');
assert.strictEqual(q.L034.category,'仕訳帳');
assert.strictEqual(q.L041.category,'仕訳帳');
assert(String(q.L034.explanation).startsWith('仕訳帳は日付、摘要欄の勘定科目、元丁、借方・貸方金額を日付順に記入します。'),'L034のauthored先頭説明を保持する');
assert(String(q.L041.explanation).startsWith('仕訳帳は日付、摘要欄の勘定科目、元丁、借方・貸方金額を日付順に記入します。'),'L041のauthored先頭説明を保持する');
for(const label of ['まずここを確認','どういう取引か考える','必要な金額を出す','最後に確認','間違えやすいところ'])assert(view.includes(label),`教材見出し「${label}」を実画面rendererに持つ`);
assert(view.includes("journalBook?'どういう取引か考える':'増減の流れをつかむ'"),'問題形式に応じて処理見出しを切り替える');
assert(view.includes("journalBook?'借方・貸方を決めて仕訳帳に記入する':'帳簿に記入する'"),'仕訳帳と元帳で記入見出しを切り替える');
assert(view.includes("...(hasMeaningfulCalculation ? [['必要な金額を出す','calculation']] : [])"),'算術計算がない問題では計算セクションを表示しない');
assert(view.includes('score.correct || !question.explanationModel'),'構造化解説は誤答かつ対象問題だけに限定する');
assert(view.includes('appendAuthoredExplanation(question, container, authoredOnly = false)'),'authored proseだけを分離表示できる');
assert(view.includes("const markers = ['【この問題への当てはめ】','【使用する資料】']"),'旧生成長文をstructured PoCへ重複表示しない');
assert(view.includes('this.appendAuthoredExplanation(question, container, true)'),'structured pathはauthored prefixだけを保持する');
assert(/\.explanation-formula strong\s*\{[^}]*overflow-wrap:\s*anywhere/s.test(css),'計算ブロックをiPhoneでクリップしない');
const feedbackIndex=html.indexOf('js/feedback.js?v=20260924-109'),modelIndex=html.indexOf('js/explanation-model.js?v=20260924-109'),viewIndex=html.indexOf('js/view.js?v=20260924-109');
assert(feedbackIndex>=0&&feedbackIndex<modelIndex&&modelIndex<viewIndex,'feedback→explanation model→viewの順に読み込む');
assert(worker.includes("'./js/explanation-model.js'"),'PWAキャッシュへexplanation modelを含める');
console.log('explanation integration tests: PASS');
