'use strict';
const assert=require('assert'),fs=require('fs'),vm=require('vm');
const view=fs.readFileSync('js/view.js','utf8'),css=fs.readFileSync('css/style.css','utf8'),html=fs.readFileSync('index.html','utf8'),worker=fs.readFileSync('service-worker.js','utf8');
const sandbox={window:{}};vm.runInNewContext(fs.readFileSync('data/questions.js','utf8'),sandbox,{filename:'data/questions.js'});
const q=sandbox.window.QuestionData;
assert(q.L034.explanationModel&&q.L041.explanationModel,'L034/L041にauthored structured explanationを持たせる');
assert.strictEqual(q.L034.explanation,'先入先出法では古い単価1,200円の商品から払い出します。払出額は25×1,200＝30,000円、残高は49個×1,200円＋20個×1,500円＝88,800円です。');
assert.strictEqual(q.L041.explanation,'現金は資産なので、借方記入で増加し、貸方記入で減少します。したがって残高は順に678,000円、591,500円です。');
for(const label of ['見る資料','取引・処理の要点','計算','仕訳・転記','検算','よくあるミス'])assert(view.includes(label),`図解見出し「${label}」を実画面rendererに持つ`);
assert(view.includes('renderStructuredExplanation(question, userAnswer, score)')&&view.includes('score.correct || !question.explanationModel'),'構造化解説は誤答かつ対象問題だけに限定する');
assert(view.includes('this.appendAuthoredExplanation(question, container)'),'既存authored explanationを図解後にも保持する');
assert(view.includes('if (structured) { container.append(structured); this.appendAuthoredExplanation(question, container); return; }'),'誤答PoCはgeneric長文手順を重複表示しない');
assert(/\.explanation-flow-section\s*\{[^}]*min-width:\s*0/s.test(css),'図解カードは狭幅で縮小可能にする');
assert(/\.explanation-formula strong\s*\{[^}]*overflow-wrap:\s*anywhere/s.test(css),'計算式をiPhoneでクリップしない');
assert(/@media \(max-width:480px\)[\s\S]*?\.explanation-transfer-card/s.test(css),'iPhone幅の転記フローを専用調整する');
const feedbackIndex=html.indexOf('js/feedback.js?v=20260924-107'),modelIndex=html.indexOf('js/explanation-model.js?v=20260924-107'),viewIndex=html.indexOf('js/view.js?v=20260924-107');
assert(feedbackIndex>=0&&feedbackIndex<modelIndex&&modelIndex<viewIndex,'feedback→explanation model→viewの順に読み込む');
assert(worker.includes("'./js/explanation-model.js'"),'PWAキャッシュへexplanation modelを含める');
console.log('explanation integration tests: PASS');
