'use strict';
const assert = require('assert'); const fs = require('fs');
const css = fs.readFileSync('css/style.css', 'utf8'); const view = fs.readFileSync('js/view.js', 'utf8');
const accountWidth = Number(css.match(/\.journal-row\s*\{[^}]*minmax\((\d+)px, 3fr\)/s)?.[1]);
assert(accountWidth >= 240, 'collapsed account selects reserve at least 240px');
assert(/\.journal-entry-area\s*\{[^}]*overflow-x:\s*auto/s.test(css), 'journal rows scroll horizontally');
assert(/@media \(max-width: 480px\)[\s\S]*?\.journal-row select,\s*\.journal-row \.amount-input\s*\{[^}]*font-size:\s*16px/s.test(css), 'mobile controls remain at least 16px');
const dateRule = css.match(/\.answer-table:not\(\.eight-column-worksheet\) \[data-column-key="date"\]\s*\{([^}]*)\}/);
const balanceRule = css.match(/\.answer-table:not\(\.eight-column-worksheet\) \[data-column-key="balance"\]\s*\{([^}]*)\}/);
const mobileOrdinaryRule = css.match(/@media \(max-width: 480px\)[\s\S]*?\.answer-table:not\(\.eight-column-worksheet\)\s*\{([^}]*)\}/);
const mobileDateRule = css.match(/@media \(max-width: 480px\)[\s\S]*?\.answer-table:not\(\.eight-column-worksheet\) \[data-column-key="date"\]\s*\{([^}]*)\}/);
const mobileDescriptionRule = css.match(/@media \(max-width: 480px\)[\s\S]*?\.answer-table:not\(\.eight-column-worksheet\) \[data-column-key="description"\]\s*\{([^}]*)\}/);
const mobileBalanceRule = css.match(/@media \(max-width: 480px\)[\s\S]*?\.answer-table:not\(\.eight-column-worksheet\) \[data-column-key="balance"\]\s*\{([^}]*)\}/);
assert(view.includes('th.dataset.columnKey = column'), 'ordinary table headers expose their semantic column key');
assert(view.includes('cell.dataset.columnKey = question.table.columns[columnIndex]'), 'ordinary table cells expose their semantic column key');
assert(dateRule && /width:\s*11ch/.test(dateRule[1]) && /min-width:\s*11ch/.test(dateRule[1]), 'date columns have a compact content-oriented width');
assert(balanceRule && /width:\s*16ch/.test(balanceRule[1]) && /min-width:\s*16ch/.test(balanceRule[1]), 'balance columns have a compact content-oriented width');
assert(mobileOrdinaryRule && /width:\s*100%/.test(mobileOrdinaryRule[1]) && /min-width:\s*0/.test(mobileOrdinaryRule[1]) && !/600px/.test(mobileOrdinaryRule[1]), 'ordinary mobile tables remove the arbitrary 600px floor');
assert(mobileDateRule && /width:\s*10ch/.test(mobileDateRule[1]) && /min-width:\s*10ch/.test(mobileDateRule[1]), 'mobile date width safely fits the longest six-character authored date');
const mobileDescriptionWidth = Number(mobileDescriptionRule?.[1].match(/min-width:\s*([\d.]+)em/)?.[1]);
assert(mobileDescriptionRule && mobileDescriptionWidth >= 7 && mobileDescriptionWidth <= 9, 'mobile description column preserves readable bookkeeping width');
assert(!/white-space:\s*nowrap/.test(mobileDescriptionRule[1]), 'mobile descriptions retain natural Japanese wrapping for exceptional long labels');
assert(mobileBalanceRule && /width:\s*13ch/.test(mobileBalanceRule[1]) && /min-width:\s*13ch/.test(mobileBalanceRule[1]), 'mobile balance width safely fits seven-character comma-formatted balances');
const mobileDateWidth = Number(mobileDateRule[1].match(/(?:^|;)\s*width:\s*(\d+)ch/)?.[1]);
const mobileBalanceWidth = Number(mobileBalanceRule[1].match(/(?:^|;)\s*width:\s*(\d+)ch/)?.[1]);
assert(mobileDateWidth <= 11 && mobileBalanceWidth < 16 && mobileDateWidth < mobileBalanceWidth, 'mobile semantic widths shrink safely and date remains narrower than balance');
assert(/\.eight-column-worksheet\s*\{[^}]*width:\s*max\(100%,\s*1320px\)/.test(css), 'eight-column worksheets retain their intentional wide canvas');
assert(mobileDescriptionRule && !/\.eight-column-worksheet(?!\))/.test(mobileDescriptionRule[0]), 'semantic description sizing explicitly excludes eight-column worksheets');
assert(/\.table-question-wrap\s*\{[^}]*overflow-x:\s*auto/.test(css), 'ordinary tables permit intentional horizontal overflow');
assert(/\.answer-table th:first-child,\s*\.answer-table td:first-child\s*\{[^}]*position:\s*sticky[^}]*left:\s*0[^}]*min-width:\s*110px/s.test(css), 'sticky first-column behavior and generic content minimum remain present');
assert(/\.table-text-input\s*\{[^}]*min-width:\s*120px/.test(css), 'ordinary free-text inputs retain their established minimum width');
assert(11 < 16, 'date is intentionally narrower than balance');
assert(/td\[data-column-key="date"\][\s\S]*td\[data-column-key="balance"\][^{]*\{[^}]*width:\s*100%[^}]*min-width:\s*0/.test(css), 'compact column inputs fill their cells without imposing the generic text minimum');
assert(!/answer-table[^\n{]*(?:date|balance)[^\n{]*:nth-child/.test(css) && !/answer-table[^\n{]*:nth-child[^\n{]*(?:date|balance)/.test(css), 'date and balance semantics never depend on column position');
assert(!/answer-table[^\n{]*:nth-child[^\n{]*description|answer-table[^\n{]*description[^\n{]*:nth-child/.test(css), 'description semantics never depend on column position');
assert(!/\[data-column-key="(?:account|item)"\]/.test(css), 'unrelated ordinary columns do not inherit compact sizing');
assert(view.includes('this.updateSelectTitle(select)'), 'selected account is also exposed as the native title');
assert(view.includes("input.setAttribute('inputmode', 'numeric')") && !view.includes('input.readOnly = true'), 'amount inputs remain editable and request a numeric mobile keyboard');
assert(view.includes("const count = mode === 'exam' ? 3"), 'exam journals use the fixed neutral three-row capacity');
for (const viewport of [320, 375, 390, 430]) {
  assert(viewport <= 480 && mobileOrdinaryRule, `${viewport}px receives the compact ordinary-table policy without disabling intrinsic overflow`);
  const minimumRowWidth = accountWidth * 2 + 120 * 2;
  assert(minimumRowWidth > viewport, `${viewport}px deliberately uses horizontal scrolling instead of shrinking four fields`);
}
console.log('mobile layout static tests (320/375/390/430): ok');
