'use strict';
const assert=require('assert'),fs=require('fs'),vm=require('vm');
const ExplanationModel=require('../js/explanation-model');
const sandbox={window:{}};vm.runInNewContext(fs.readFileSync('data/questions.js','utf8'),sandbox,{filename:'data/questions.js'});
const questions=sandbox.window.QuestionData;
const diagnostics=[{kind:'cell',title:'残高を見直します',reason:'入力値が正答と異なります。',nextRule:'直前残高から増減を反映します。',cause:'ledger:balance'}];
const l041=ExplanationModel.build(questions.L041,{cells:{r2_balance:600000,r3_balance:''}},{correct:false},{diagnostics});
assert.strictEqual(ExplanationModel.validate(l041).valid,true);
assert(ExplanationModel.REQUIRED_SECTIONS.every(key=>Array.isArray(l041[key])));
assert(l041.calculation.some(item=>item.expression==='505,000 + 173,000 = 678,000'));
assert(l041.calculation.some(item=>item.expression==='678,000 − 86,500 = 591,500'));
assert.strictEqual(l041.fallback.authoredExplanation,questions.L041.explanation);
assert.strictEqual(l041.mistakes[0].title,diagnostics[0].title);
const l034=ExplanationModel.build(questions.L034,{}, {correct:false},{diagnostics});
assert(l034.calculation.some(item=>item.expression==='25 × 1,200 = 30,000'));
assert(l034.calculation.some(item=>item.expression==='49 × 1,200 + 20 × 1,500 = 88,800'));
assert(l034.transfer.some(item=>String(item.value).includes('88,800')));
assert.strictEqual(l034.fallback.authoredExplanation,questions.L034.explanation);
assert.strictEqual(ExplanationModel.validate({}).valid,false);
console.log('structured explanation model tests: PASS');
