'use strict';
const assert=require('assert'),fs=require('fs'),vm=require('vm');
const ExplanationModel=require('../js/explanation-model');
const sandbox={window:{}};vm.runInNewContext(fs.readFileSync('data/questions.js','utf8'),sandbox,{filename:'data/questions.js'});
const questions=sandbox.window.QuestionData;
const diagnostics=[{kind:'cell',title:'元丁を見直します',reason:'入力値が正答と異なります。',nextRule:'資料→科目→貸借→元丁の順に照合します。',cause:'ledger:folio'}];
assert.strictEqual(questions.L034.category,'仕訳帳');
assert.strictEqual(questions.L041.category,'仕訳帳');
const l034=ExplanationModel.build(questions.L034,{cells:{}},{correct:false},{diagnostics});
assert.strictEqual(ExplanationModel.validate(l034).valid,true);
assert(ExplanationModel.REQUIRED_SECTIONS.every(key=>Array.isArray(l034[key])));
assert(l034.calculation.some(item=>item.expression==='90,000円（売上票の記載額）'));
assert(l034.calculation.some(item=>item.expression==='12,000円（領収証の記載額）'));
assert(l034.transfer.some(item=>item.to==='借方：売掛金（元丁113）'));
assert(l034.transfer.some(item=>item.to==='貸方：現金（元丁101）'));
assert.strictEqual(l034.mistakes[0].title,diagnostics[0].title);
const l041=ExplanationModel.build(questions.L041,{cells:{}},{correct:false},{diagnostics});
assert(l041.calculation.some(item=>item.expression==='90,000円（取引資料の記載額）'));
assert(l041.calculation.some(item=>item.expression==='12,000円（取引資料の記載額）'));
assert(l041.checks.some(item=>String(item.expected).includes('売掛金113')));
assert(String(l041.fallback.authoredExplanation).includes('仕訳帳は日付'));
assert.strictEqual(ExplanationModel.validate({}).valid,false);
console.log('structured explanation model tests: PASS');
