'use strict';
const assert=require('assert');
const crypto=require('crypto');
const fs=require('fs');
const path=require('path');
const childProcess=require('child_process');
const core=require('../../scripts/qa/audit-core');
const lifecycle=require('../../scripts/qa/phase-b-lifecycle');
const authorityPath=generation=>path.join(core.ROOT,`reports/auto-gate/audit-locks/phase-b-generation-${generation}.json`);
const auditPath=path.join(core.ROOT,'independent-audit/manifest.json');
const authorityBytes=new Map([2,3,4,5,6,7].filter(generation=>fs.existsSync(authorityPath(generation))).map(generation=>[generation,fs.readFileSync(authorityPath(generation))]));
const auditBytes=fs.readFileSync(auditPath);
const committed=generation=>childProcess.spawnSync('git',['cat-file','-e',`HEAD:reports/auto-gate/audit-locks/phase-b-generation-${generation}.json`],{cwd:core.ROOT}).status===0;
const digest=value=>crypto.createHash('sha256').update(value).digest('hex');
let count=0;const test=(name,fn)=>{fn();count++;console.log(`ok ${count} - ${name}`);};
const rejectCandidate=(candidate,generations)=>assert.strictEqual(lifecycle.verifyCandidate(candidate,{generations}).ok,false);
try{
  const authorities=lifecycle.generationAuthorities(),generations=authorities.map(item=>item.document.generation),generation7Committed=committed(7);
  test('authority sequence is [2,3,4,5,6] before Generation 7 or [2,3,4,5,6,7] after commit',()=>assert.deepStrictEqual(generations,generation7Committed?[2,3,4,5,6,7]:[2,3,4,5,6]));
  for(const generation of generations)test(`Generation ${generation} worktree bytes remain immutable`,()=>assert(authorities.find(item=>item.document.generation===generation).bytes.equals(authorityBytes.get(generation))));
  for(let index=1;index<authorities.length;index++)test(`Generation ${generations[index]} predecessor is exact Generation ${generations[index-1]} identity`,()=>assert.deepStrictEqual(authorities[index].document.predecessor,lifecycle.identity(authorities[index-1].document)));
  test('authority identities are content-based',()=>{for(const authority of authorities){assert.strictEqual(lifecycle.identity(authority.document).canonicalDocumentSha256,lifecycle.canonicalDocumentHash(authority.document));assert(!Object.hasOwn(lifecycle.identity(authority.document),'commit'));}});
  for(const generation of generations)test(`Generation ${generation} trailing-byte tamper is rejected`,()=>{const target=authorityPath(generation),saved=authorityBytes.get(generation);fs.writeFileSync(target,Buffer.concat([saved,Buffer.from(' ')]));assert(lifecycle.verifyCurrent().errors.includes(`reports/auto-gate/audit-locks/phase-b-generation-${generation}.json raw bytes differ from immutable historical authority`));fs.writeFileSync(target,saved);});
  const documents=authorities.map(item=>item.document),candidate=generation7Committed?documents.at(-1):lifecycle.createCandidate();
  for(const generation of [2,3,4,5,6,7])test(`duplicate Generation ${generation} is rejected`,()=>{const existing=documents.find(document=>document.generation===generation)||candidate;rejectCandidate(candidate,[...documents,structuredClone(existing)]);});
  test('skipped Generation 7 is rejected',()=>{const skipped=structuredClone(candidate);skipped.generation=8;rejectCandidate(skipped,documents);});
  test('competing Generation 7 is rejected',()=>{const fork=structuredClone(candidate);fork.auditHash='f'.repeat(64);rejectCandidate(candidate,[...documents.filter(document=>document.generation<7),fork]);});
  test('broken Generation 7 predecessor is rejected',()=>{const broken=structuredClone(candidate);broken.predecessor.canonicalDocumentSha256='0'.repeat(64);rejectCandidate(broken,documents.filter(document=>document.generation<7));});
  test('coordinated audit and historical authority tamper is rejected',()=>{fs.writeFileSync(auditPath,Buffer.concat([auditBytes,Buffer.from(' ')]));const target=authorityPath(2),value=JSON.parse(authorityBytes.get(2)),relative='independent-audit/manifest.json';value.files[relative]=digest(fs.readFileSync(auditPath));value.auditHash=digest(JSON.stringify(value.files));fs.writeFileSync(target,JSON.stringify(value,null,2)+'\n');const errors=lifecycle.verifyCurrent().errors;assert(errors.includes('reports/auto-gate/audit-locks/phase-b-generation-2.json raw bytes differ from immutable historical authority'));assert(errors.includes(relative));fs.writeFileSync(target,authorityBytes.get(2));fs.writeFileSync(auditPath,auditBytes);});
  if(generation7Committed)test('committed Generation 7 current integrity passes',()=>assert.strictEqual(lifecycle.verifyCurrent().ok,true));
}finally{fs.writeFileSync(auditPath,auditBytes);for(const [generation,bytes] of authorityBytes)fs.writeFileSync(authorityPath(generation),bytes);}
console.log(`Generation authority successor-aware immutability regressions: ${count}/${count}`);
