'use strict';
const assert=require('assert'),childProcess=require('child_process'),crypto=require('crypto'),fs=require('fs');
const core=require('../../scripts/qa/audit-core'),lifecycle=require('../../scripts/qa/phase-b-lifecycle'),finalizer=require('../../scripts/qa/finalize-phase-b-generation-46');
let count=0;const test=(name,fn)=>{fn();count++;console.log(`ok ${count} - ${name}`);};const digest=bytes=>crypto.createHash('sha256').update(bytes).digest('hex');
const authorities=lifecycle.generationAuthorities(),g45=authorities.find(x=>x.document.generation===45),g46=authorities.find(x=>x.document.generation===46);
test('Generation 46 is discoverable',()=>assert(g46));
test('Generation 46 predecessor is exact Generation 45',()=>assert.deepStrictEqual(g46.document.predecessor,lifecycle.identity(g45.document)));
test('Generation 46 production identity changes for source-table guidance',()=>assert.notStrictEqual(g46.document.baselineIdentity,g45.document.baselineIdentity));
test('committed Generation 46 current integrity passes',()=>assert.strictEqual(lifecycle.verifyCurrent().ok,true));
test('duplicate Generation 46 issuance fails',()=>assert.notStrictEqual(childProcess.spawnSync(process.execPath,['scripts/qa/finalize-phase-b-generation-46.js'],{cwd:core.ROOT,encoding:'utf8'}).status,0));
test('historical authority raw SHA values are pinned',()=>assert.deepStrictEqual(finalizer.authorityPaths.map(f=>digest(fs.readFileSync(f))),finalizer.expectedAuthoritySha256));
console.log(`Generation 46 finalizer regressions: ${count}/${count}`);
