'use strict';
const assert=require('assert'),childProcess=require('child_process'),crypto=require('crypto'),fs=require('fs');
const core=require('../../scripts/qa/audit-core'),lifecycle=require('../../scripts/qa/phase-b-lifecycle'),finalizer=require('../../scripts/qa/finalize-phase-b-generation-16');
let count=0;const test=(n,f)=>{f();count++;console.log(`ok ${count} - ${n}`);},digest=b=>crypto.createHash('sha256').update(b).digest('hex');
const authorities=lifecycle.generationAuthorities(),g15=authorities.find(x=>x.document.generation===15),g16=authorities.find(x=>x.document.generation===16);
test('Generation 16 is discoverable',()=>assert(g16));
test('Generation 16 predecessor is exact Generation 15',()=>assert.deepStrictEqual(g16.document.predecessor,lifecycle.identity(g15.document)));
test('committed Generation 16 current integrity passes',()=>assert.strictEqual(lifecycle.verifyCurrent().ok,true));
test('duplicate Generation 16 issuance fails',()=>assert.notStrictEqual(childProcess.spawnSync(process.execPath,['scripts/qa/finalize-phase-b-generation-16.js'],{cwd:core.ROOT,encoding:'utf8'}).status,0));
test('historical authority raw SHA values are pinned',()=>assert.deepStrictEqual(finalizer.authorityPaths.map(f=>digest(fs.readFileSync(f))),finalizer.expectedAuthoritySha256));
console.log(`Generation 16 finalizer regressions: ${count}/${count}`);
