'use strict';
const assert=require('assert'),childProcess=require('child_process'),crypto=require('crypto'),fs=require('fs');
const core=require('../../scripts/qa/audit-core'),lifecycle=require('../../scripts/qa/phase-b-lifecycle'),finalizer=require('../../scripts/qa/finalize-phase-b-generation-42');
let count=0;const test=(name,fn)=>{fn();count++;console.log(`ok ${count} - ${name}`);};const digest=bytes=>crypto.createHash('sha256').update(bytes).digest('hex');
const authorities=lifecycle.generationAuthorities(),g41=authorities.find(x=>x.document.generation===41),g42=authorities.find(x=>x.document.generation===42);
test('Generation 42 is discoverable',()=>assert(g42));
test('Generation 42 predecessor is exact Generation 41',()=>assert.deepStrictEqual(g42.document.predecessor,lifecycle.identity(g41.document)));
test('Generation 42 production identity changes for Chapter 8 explanation coverage',()=>assert.notStrictEqual(g42.document.baselineIdentity,g41.document.baselineIdentity));
test('committed Generation 42 current integrity passes',()=>assert.strictEqual(lifecycle.verifyCurrent().ok,true));
test('duplicate Generation 42 issuance fails',()=>assert.notStrictEqual(childProcess.spawnSync(process.execPath,['scripts/qa/finalize-phase-b-generation-42.js'],{cwd:core.ROOT,encoding:'utf8'}).status,0));
test('historical authority raw SHA values are pinned',()=>assert.deepStrictEqual(finalizer.authorityPaths.map(f=>digest(fs.readFileSync(f))),finalizer.expectedAuthoritySha256));
console.log(`Generation 42 finalizer regressions: ${count}/${count}`);
