'use strict';
const fs=require('fs'),path=require('path'),crypto=require('crypto'),os=require('os'),vm=require('vm'),childProcess=require('child_process');
const ROOT=path.resolve(__dirname,'../..');
const read=p=>fs.readFileSync(path.join(ROOT,p),'utf8');
const sha=p=>crypto.createHash('sha256').update(fs.readFileSync(path.join(ROOT,p))).digest('hex');
const json=p=>JSON.parse(read(p));
const walk=dir=>fs.readdirSync(path.join(ROOT,dir),{withFileTypes:true}).flatMap(e=>e.isDirectory()?walk(`${dir}/${e.name}`):[`${dir}/${e.name}`]).sort();
const productionFiles=()=>['data','js','css','types'].flatMap(walk).concat(['index.html','service-worker.js']).sort();
function loadProduction(root=ROOT){const source=p=>fs.readFileSync(path.join(root,p),'utf8');const window={};const context={window,console,Event:function(){},queueMicrotask};vm.runInNewContext(source('data/questions.js'),context,{filename:'data/questions.js'});vm.runInNewContext(source('data/accounting-domain.js'),context,{filename:'data/accounting-domain.js'});vm.runInNewContext(source('js/controller.js'),context,{filename:'js/controller.js'});return {questions:window.QuestionData,exam:window.ExamPoolDefinition,domain:window.AccountingDomain,Controller:window.AppController,root};}
function lockCheck(){
 const file=path.join(ROOT,'reports/auto-gate/audit-lock.json');
 if(!fs.existsSync(file))return {ok:false,errors:['lock missing']};
 let lock;try{lock=JSON.parse(fs.readFileSync(file));}catch(_){return {ok:false,errors:['lock invalid JSON']};}
 const errors=[];
 for(const [p,h] of Object.entries(lock.files||{}))if(!fs.existsSync(path.join(ROOT,p))||sha(p)!==h)errors.push(p);
 const current=[...walk('independent-audit'),...walk('scripts/qa')];for(const p of current)if(!(p in (lock.files||{})))errors.push(`unlocked:${p}`);
 let versions=[];
 if(lock.lockSchemaVersion===2){
  if(lock.phase!=='A_FINAL_IMMUTABLE_BASELINE'||lock.baselineVersion!==1||lock.algorithm!=='sha256')errors.push('invalid Final V2 metadata');
  const auditHash=crypto.createHash('sha256').update(JSON.stringify(lock.files)).digest('hex');if(lock.auditHash!==auditHash)errors.push('auditHash mismatch');
  const productionHashes=Object.fromEntries(productionFiles().map(p=>[p,sha(p)])),baselineIdentity=crypto.createHash('sha256').update(JSON.stringify({auditHash,productionHashes})).digest('hex');if(lock.baselineIdentity!==baselineIdentity)errors.push('baselineIdentity mismatch');
  try{const commits=childProcess.execFileSync('git',['log','--format=%H','--','reports/auto-gate/audit-lock.json'],{cwd:ROOT,encoding:'utf8'}).trim().split(/\s+/u).filter(Boolean);versions=commits.flatMap(commit=>{try{const value=JSON.parse(childProcess.execFileSync('git',['show',`${commit}:reports/auto-gate/audit-lock.json`],{cwd:ROOT,encoding:'utf8'}));return value.lockSchemaVersion===2?[{commit,value}]:[];}catch(_){return [];}});}catch(_){errors.push('git history unavailable');}
  if(versions.length===0){if(process.env.AUDIT_LOCK_ALLOW_PENDING_BASELINE!=='1')errors.push('Final V2 is not committed');}else{if(versions.length!==1)errors.push(`reachable Final V2 count ${versions.length}`);if(JSON.stringify(versions.at(-1).value)!==JSON.stringify(lock))errors.push('current lock differs from immutable Final V2 authority');}
 }
 return {ok:errors.length===0,errors:[...new Set(errors)],hash:lock.auditHash,baselineIdentity:lock.baselineIdentity,reachableFinalV2:versions.length,lock};
}
function actualStoryRun(prod){const C=prod.Controller.prototype;const fake={questions:prod.questions,ids:Object.keys(prod.questions),currentId:null,examCandidateIds:C.examCandidateIds,learningIds:C.learningIds,storyIds:C.storyIds,modeIds:C.modeIds,model:{state:{mode:'story',answeredIds:[],reviewSchedule:{}},recommendedIds:()=>[]},start(id){this.currentId=id;this.visited.push(id);return true;},visited:[],renderModes(){this.terminated=true;},showMode(){this.terminated=true;}};const ids=C.storyIds.call(fake);if(ids[0])fake.start(ids[0]);const seen=new Set();while(fake.currentId&&!fake.terminated&&fake.visited.length<=ids.length+2){if(seen.has(fake.currentId))break;seen.add(fake.currentId);fake.model.state.answeredIds.push(fake.currentId);C.next.call(fake);}return {ids,visited:fake.visited,terminated:fake.terminated,loop:fake.visited.length!==new Set(fake.visited).size};}
function assessStoryMetrics(expectedDisplayedCount,ids,visited){const visitedPositions=visited.map(id=>ids.indexOf(id)+1).filter(position=>position>0);let positionGap=0;for(let i=1;i<visitedPositions.length;i++)if(visitedPositions[i]!==visitedPositions[i-1]+1)positionGap++;return {expectedDisplayedCount,actualStorySequenceCount:ids.length,reachableCount:new Set(visited).size,visitedPositions,positionGap,prematureTermination:visited.length<ids.length?1:0,unexpectedLoop:visited.length===new Set(visited).size?0:1,unreachable:ids.filter(id=>!visited.includes(id)),displayCountMismatch:ids.length===expectedDisplayedCount?0:1};}
function audit(prod){const q=prod.questions,g=json('independent-audit/golden/known-critical.json'),storySpec=json('independent-audit/golden/story-sequence.json');const findings=[];const add=(gate,code,id,detail)=>findings.push({gate,code,id,detail});
 const ids=Object.keys(q);if(ids.length!==300)add('GATE-01','COVERAGE_TOTAL',null,ids.length);if(new Set(ids).size!==ids.length)add('GATE-01','DUPLICATE_ID');for(const id of g.ids)if(!q[id])add('GATE-01','MISSING_GOLDEN',id);
 if(!/先入先出法/.test(q.L004?.question||''))add('GATE-04','FIFO_METHOD','L004');if(/移動平均/.test(q.L004?.explanation||''))add('GATE-04','FIFO_CONTAMINATION','L004');
 if(/44円/.test(JSON.stringify(q.L004)))add('GATE-01','QUANTITY_AS_YEN','L004');if(/5円/.test(q.L005?.question||''))add('GATE-01','LIFE_AS_YEN','L005');
 for(const [k,v] of Object.entries(g.facts.L004.cells))if(q.L004?.answer?.cells?.[k]!==v)add('GATE-04','FIXED_EXPECTED','L004',k);
 if(q.L040?.answer?.cells?.depreciationA!==60000||q.L040?.answer?.cells?.depreciationB!==45000)add('GATE-04','FIXED_EXPECTED','L040');
 if(q.L041?.answer?.cells?.d1Ref!==113)add('GATE-04','FOLIO_EXPECTED','L041');
 const l40=JSON.stringify(q.L040);if(/60,?000か月/.test(l40))add('GATE-01','AMOUNT_AS_MONTH','L040');if(/113円/.test(JSON.stringify(q.L041)))add('GATE-01','FOLIO_AS_YEN','L041');
 for(const id of ['J017','J050']){const text=JSON.stringify(q[id]);const forbidden=id==='J017'?/現金過不足.{0,20}(通常の)?資産/:/損益.{0,20}(通常の)?純資産/;if(forbidden.test(text))add('GATE-03','SPECIAL_ACCOUNT_MISCLASSIFIED',id);}
 if(prod.domain.accountType('損益')!=='closing')add('GATE-03','PROFIT_CLASSIFICATION');if(prod.domain.accountType('現金過不足')!=='temporary')add('GATE-03','CASH_OVER_SHORT_CLASSIFICATION');
 if(/内部ID\s+r3_amount/.test(JSON.stringify(q.L004)))add('GATE-02','RAW_INTERNAL_ID','L004');
 for(const id of g.ids){const x=q[id];if(!x)continue;const explanation=x.explanation||'';const answerValues=Object.values(x.answer?.cells||{}).concat((x.answer?.debit||[]).flatMap(e=>[e.account,e.amount]),(x.answer?.credit||[]).flatMap(e=>[e.account,e.amount]));const concrete=answerValues.some(v=>explanation.includes(typeof v==='number'?v.toLocaleString('ja-JP'):String(v)));if(explanation.length<80||!concrete)add('GATE-02','EXPLANATION_RELATION_INCOMPLETE',id,'must connect evidence, judgment, calculation, answer');}
 for(const id of ['F002','F003','F010']){const cells=q[id]?.answer?.cells||{};if(cells.assetsTotal!==cells.liabilitiesEquityTotal)add('GATE-08','ACCOUNTING_EQUATION',id);}
 const bsSections=q.F002?.table?.rows?.map(row=>row.section)||[];if(!bsSections.includes('純資産'))add('GATE-12','DUPLICATE_BS_SECTION','F002');
 const run=actualStoryRun(prod),required=storySpec.requiredRun,displayCount=storySpec.displayCount;for(const id of required)if(!run.visited.includes(id))add('GATE-10','UNREACHABLE_STORY_QUESTION',id);for(let i=0;i<required.length-1;i++){const at=run.visited.indexOf(required[i]);if(at<0||run.visited[at+1]!==required[i+1])add('GATE-10','PREMATURE_STORY_TERMINATION',required[i],`expected next ${required[i+1]}`);}if(run.loop)add('GATE-10','UNEXPECTED_LOOP');if(run.ids.length!==displayCount)add('GATE-10','PROGRESS_COUNT_MISMATCH',null,{expectedDisplayedCount:displayCount,actualStorySequenceCount:run.ids.length});
 const metrics=assessStoryMetrics(displayCount,run.ids,run.visited);if(metrics.positionGap)add('GATE-10','STORY_POSITION_GAP',null,metrics.visitedPositions);
 const comprehensive=Object.keys(q).filter(id=>id.startsWith('C')).sort(),signature=x=>JSON.stringify({category:x.category,question:x.question,materials:x.materials,answer:x.answer,explanation:x.explanation});for(let i=0;i<comprehensive.length-1;i++)for(let j=i+1;j<comprehensive.length;j++)if(signature(q[comprehensive[i]])===signature(q[comprehensive[j]]))add('GATE-11','EXCESSIVE_REPETITION',comprehensive[i],comprehensive[j]);
 const css=fs.readFileSync(path.join(prod.root||ROOT,'css/style.css'),'utf8');if(/font-size\s*:\s*15px/.test(css))add('GATE-13','MOBILE_FONT_TOO_SMALL');
 return {findings,story:{...metrics,prematureTermination:findings.filter(x=>x.code==='PREMATURE_STORY_TERMINATION').length,unreachable:findings.filter(x=>x.code==='UNREACHABLE_STORY_QUESTION').map(x=>x.id),ROUTING_INTEGRATION:'TESTED',BROWSER_E2E:'UNVERIFIED',browserE2EPlan:'Phase C'}};}
const mutationCases=[
 ['FIFO_TO_MOVING_AVERAGE','data/questions.js','FIFO_METHOD',s=>s.replace('商品有高帳を先入先出法で完成させなさい。','商品有高帳を移動平均法で完成させなさい。')],
 ['MOVING_AVERAGE_TO_FIFO','data/questions.js','FIFO_CONTAMINATION',s=>mutateQuestionBlock(s,'L004',b=>b.replace('"explanation": "','"explanation": "移動平均 '))],
 ['QUANTITY_TO_YEN','data/questions.js','QUANTITY_AS_YEN',s=>s.replace('"quantity": 44,','"quantity": "44円",')],
 ['LIFE_TO_YEN','data/questions.js','LIFE_AS_YEN',s=>s.replace('取得原価・耐用年数・期首減価償却累計額から','取得原価・耐用年数5円・期首減価償却累計額から')],
 ['FOLIO_TO_YEN','data/questions.js','FOLIO_AS_YEN',s=>s.replace('元丁は現金101、売掛金113、売上401、通信費521','元丁は現金101、売掛金113円、売上401、通信費521')],
 ['AMOUNT_TO_MONTH','data/questions.js','AMOUNT_AS_MONTH',s=>appendProductionMutation(s,"QuestionData.L040.answer.cells.depreciationA = '60,000か月';")],
 ['PROFIT_TO_EQUITY','data/accounting-domain.js','PROFIT_CLASSIFICATION',s=>s.replace("closing: ['損益']","closing: [], equity: ['損益']")],
 ['CASH_OVER_SHORT_TO_ASSET','data/accounting-domain.js','CASH_OVER_SHORT_CLASSIFICATION',s=>s.replace("temporary: ['現金過不足']","temporary: [], asset: ['現金過不足']")],
 ['RAW_INTERNAL_ID','data/questions.js','RAW_INTERNAL_ID',s=>s.replace('商品有高帳を先入先出法で完成させなさい。','商品有高帳を先入先出法で完成させなさい。内部ID r3_amount')],
 ['REMOVE_FORMULA','data/questions.js','EXPLANATION_RELATION_INCOMPLETE',s=>appendProductionMutation(s,"QuestionData.L004.explanation = '';" )],
 ['REMOVE_CORRECT_ACCOUNT','data/questions.js','EXPLANATION_RELATION_INCOMPLETE',s=>appendProductionMutation(s,"QuestionData.J017.explanation = '';" )],
 ['REMOVE_CORRECT_AMOUNT','data/questions.js','EXPLANATION_RELATION_INCOMPLETE',s=>appendProductionMutation(s,"QuestionData.L040.explanation = '';" )],
 ['DUPLICATE_BS_SECTION','data/questions.js','DUPLICATE_BS_SECTION',s=>mutateQuestionBlock(s,'F002',b=>b.replaceAll('"section": "純資産"','"section": "負債"'))],
 ['FONT_SIZE_15PX','css/style.css','MOBILE_FONT_TOO_SMALL',s=>s.replace('font-size: 16px;','font-size: 15px;')],
 ['STORY_ITEM_TO_EXAM_POOL','data/questions.js','UNREACHABLE_STORY_QUESTION',s=>appendProductionMutation(s,"QuestionData.C004.learningRole = 'transfer';").replace("'C001','C002','C003','C006'","'C001','C002','C003','C004','C006'")],
 ['NEXT_SELF_LOOP','js/controller.js','UNEXPECTED_LOOP',s=>s.replace('ids[ids.indexOf(this.currentId) + 1]','ids[ids.indexOf(this.currentId)]')],
 ['NEXT_NULL_AT_20','js/controller.js','UNREACHABLE_STORY_QUESTION',s=>s.replace('return this.learningIds().map((id, index)','return this.learningIds().slice(0, 20).map((id, index)')],
 ['DISPLAY_25_REACH_20','js/controller.js','PROGRESS_COUNT_MISMATCH',s=>s.replace('return this.learningIds().map((id, index)','return this.learningIds().slice(0, 20).map((id, index)')],
 ['C004_C010_IDENTICAL','data/questions.js','EXCESSIVE_REPETITION',s=>appendProductionMutation(s,"Object.assign(QuestionData.C010, { category:QuestionData.C004.category, question:QuestionData.C004.question, materials:QuestionData.C004.materials, table:QuestionData.C004.table, answer:QuestionData.C004.answer, explanation:QuestionData.C004.explanation });")]
];
function mutateQuestionBlock(source,id,change){const start=source.indexOf(`  "${id}": {`);if(start<0)throw new Error(`question block not found: ${id}`);const tail=source.slice(start+1),next=/\n  "[A-Z]\d{3}": \{/u.exec(tail),end=next?start+1+next.index:source.lastIndexOf('\n};');if(end<start)throw new Error(`question block end not found: ${id}`);return source.slice(0,start)+change(source.slice(start,end))+source.slice(end);}
function appendProductionMutation(source,statement){return source.replace("if (typeof window !== 'undefined') {",`${statement}\n\nif (typeof window !== 'undefined') {`);}
const findingKey=finding=>JSON.stringify({gate:finding.gate,code:finding.code,id:finding.id??null,detail:finding.detail??null});
function findingDelta(baselineFindings,mutantFindings,expectedFailureCode){const subtract=(left,right)=>{const remaining=right.map(f=>({key:findingKey(f),used:false}));return left.filter(f=>{const match=remaining.find(x=>!x.used&&x.key===findingKey(f));if(match){match.used=true;return false;}return true;});};const baselineMatchingFindings=baselineFindings.filter(f=>f.code===expectedFailureCode),mutantMatchingFindings=mutantFindings.filter(f=>f.code===expectedFailureCode),introducedFindings=subtract(mutantFindings,baselineFindings),removedFindings=subtract(baselineFindings,mutantFindings);return {baselineMatchingFindings,mutantMatchingFindings,introducedFindings,removedFindings,causalDeltaConfirmed:introducedFindings.some(f=>f.code===expectedFailureCode)};}
function mutations(){const required=json('independent-audit/mutations/required.json').required;return mutationCases.map(([id,target,expectedFailureCode,mutate])=>{if(!required.includes(id))throw new Error(`undeclared mutation: ${id}`);const temporaryRoot=fs.mkdtempSync(path.join(os.tmpdir(),'boki-production-mutation-'));try{for(const file of productionFiles()){const destination=path.join(temporaryRoot,file);fs.mkdirSync(path.dirname(destination),{recursive:true});fs.copyFileSync(path.join(ROOT,file),destination);}const baselineFindings=audit(loadProduction(temporaryRoot)).findings,targetPath=path.join(temporaryRoot,target),before=fs.readFileSync(targetPath),after=Buffer.from(mutate(before.toString('utf8')));if(before.equals(after))throw new Error(`mutation made no change: ${id}`);fs.writeFileSync(targetPath,after);const mutantFindings=audit(loadProduction(temporaryRoot)).findings,delta=findingDelta(baselineFindings,mutantFindings,expectedFailureCode),actualFailureCode=delta.introducedFindings.find(f=>f.code===expectedFailureCode)?.code||null;return {mutationId:id,targetProductionFile:target,beforeHash:crypto.createHash('sha256').update(before).digest('hex'),afterHash:crypto.createHash('sha256').update(after).digest('hex'),expectedFailureCode,actualFailureCode,baselineFindings,mutantFindings,...delta,status:delta.causalDeltaConfirmed?'KILLED':'SURVIVED'};}catch(error){return {mutationId:id,targetProductionFile:target,expectedFailureCode,actualFailureCode:'MUTATION_RUNNER_ERROR',baselineFindings:[],mutantFindings:[],baselineMatchingFindings:[],mutantMatchingFindings:[],introducedFindings:[],removedFindings:[],causalDeltaConfirmed:false,status:'SURVIVED',error:error.message};}finally{fs.rmSync(temporaryRoot,{recursive:true,force:true});}});}
module.exports={ROOT,read,sha,json,walk,productionFiles,loadProduction,lockCheck,assessStoryMetrics,audit,findingDelta,mutations};
