'use strict';
const fs=require('fs'),path=require('path'),crypto=require('crypto'),vm=require('vm');
const ROOT=path.resolve(__dirname,'../..');
const read=p=>fs.readFileSync(path.join(ROOT,p),'utf8');
const sha=p=>crypto.createHash('sha256').update(fs.readFileSync(path.join(ROOT,p))).digest('hex');
const json=p=>JSON.parse(read(p));
const walk=dir=>fs.readdirSync(path.join(ROOT,dir),{withFileTypes:true}).flatMap(e=>e.isDirectory()?walk(`${dir}/${e.name}`):[`${dir}/${e.name}`]).sort();
const productionFiles=()=>['data','js','css','types'].flatMap(walk).concat(['index.html','service-worker.js']).sort();
function loadProduction(){const window={};const context={window,console,Event:function(){},queueMicrotask};vm.runInNewContext(read('data/questions.js'),context,{filename:'data/questions.js'});vm.runInNewContext(read('js/controller.js'),context,{filename:'js/controller.js'});return {questions:window.QuestionData,exam:window.ExamPoolDefinition,Controller:window.AppController};}
function lockCheck(){const file=path.join(ROOT,'reports/auto-gate/audit-lock.json');if(!fs.existsSync(file))return {ok:false,errors:['lock missing']};const lock=JSON.parse(fs.readFileSync(file));const errors=[];for(const [p,h] of Object.entries(lock.files)){if(!fs.existsSync(path.join(ROOT,p))||sha(p)!==h)errors.push(p);}const current=[...walk('independent-audit'),...walk('scripts/qa')].filter(p=>p!=='scripts/qa/create-audit-lock.js');for(const p of current)if(!(p in lock.files))errors.push(`unlocked:${p}`);return {ok:errors.length===0,errors,hash:lock.auditHash};}
function actualStoryRun(prod){const C=prod.Controller.prototype;const fake={questions:prod.questions,ids:Object.keys(prod.questions),currentId:null,examCandidateIds:C.examCandidateIds,learningIds:C.learningIds,storyIds:C.storyIds,modeIds:C.modeIds,model:{state:{mode:'story',answeredIds:[],reviewSchedule:{}},recommendedIds:()=>[]},start(id){this.currentId=id;this.visited.push(id);return true;},visited:[],renderModes(){this.terminated=true;},showMode(){this.terminated=true;}};const ids=C.storyIds.call(fake);if(ids[0])fake.start(ids[0]);const seen=new Set();while(fake.currentId&&!fake.terminated&&fake.visited.length<=ids.length+2){if(seen.has(fake.currentId))break;seen.add(fake.currentId);fake.model.state.answeredIds.push(fake.currentId);C.next.call(fake);}return {ids,visited:fake.visited,terminated:fake.terminated,loop:fake.visited.length!==new Set(fake.visited).size};}
function audit(prod){const q=prod.questions,g=json('independent-audit/golden/known-critical.json'),storySpec=json('independent-audit/golden/story-sequence.json');const findings=[];const add=(gate,code,id,detail)=>findings.push({gate,code,id,detail});
 const ids=Object.keys(q);if(ids.length!==300)add('GATE-01','COVERAGE_TOTAL',null,ids.length);if(new Set(ids).size!==ids.length)add('GATE-01','DUPLICATE_ID');for(const id of g.ids)if(!q[id])add('GATE-01','MISSING_GOLDEN',id);
 if(!/先入先出法/.test(q.L004?.question||''))add('GATE-04','FIFO_METHOD','L004');if(/移動平均/.test(q.L004?.explanation||''))add('GATE-04','FIFO_CONTAMINATION','L004');
 for(const [k,v] of Object.entries(g.facts.L004.cells))if(q.L004?.answer?.cells?.[k]!==v)add('GATE-04','FIXED_EXPECTED','L004',k);
 if(q.L040?.answer?.cells?.depreciationA!==60000||q.L040?.answer?.cells?.depreciationB!==45000)add('GATE-04','FIXED_EXPECTED','L040');
 if(q.L041?.answer?.cells?.d1Ref!==113)add('GATE-04','FOLIO_EXPECTED','L041');
 const l40=JSON.stringify(q.L040);if(/60,?000か月/.test(l40))add('GATE-01','AMOUNT_AS_MONTH','L040');if(/113円/.test(JSON.stringify(q.L041)))add('GATE-01','FOLIO_AS_YEN','L041');
 for(const id of ['J017','J050']){const text=JSON.stringify(q[id]);const forbidden=id==='J017'?/現金過不足.{0,20}(通常の)?資産/:/損益.{0,20}(通常の)?純資産/;if(forbidden.test(text))add('GATE-03','SPECIAL_ACCOUNT_MISCLASSIFIED',id);}
 for(const id of g.ids){const x=q[id];if(!x)continue;const explanation=x.explanation||'';const answerValues=Object.values(x.answer?.cells||{}).concat((x.answer?.debit||[]).flatMap(e=>[e.account,e.amount]),(x.answer?.credit||[]).flatMap(e=>[e.account,e.amount]));const concrete=answerValues.some(v=>explanation.includes(typeof v==='number'?v.toLocaleString('ja-JP'):String(v)));if(explanation.length<80||!concrete)add('GATE-02','EXPLANATION_RELATION_INCOMPLETE',id,'must connect evidence, judgment, calculation, answer');}
 for(const id of ['F002','F003','F010']){const cells=q[id]?.answer?.cells||{};if(cells.assetsTotal!==cells.liabilitiesEquityTotal)add('GATE-08','ACCOUNTING_EQUATION',id);}
 const run=actualStoryRun(prod),required=storySpec.requiredRun;for(const id of required)if(!run.visited.includes(id))add('GATE-10','UNREACHABLE_STORY_QUESTION',id);for(let i=0;i<required.length-1;i++){const at=run.visited.indexOf(required[i]);if(at<0||run.visited[at+1]!==required[i+1])add('GATE-10','PREMATURE_STORY_TERMINATION',required[i],`expected next ${required[i+1]}`);}if(run.loop)add('GATE-10','UNEXPECTED_LOOP');if(run.ids.length%25!==0)add('GATE-10','PROGRESS_COUNT_MISMATCH',null,run.ids.length);
 const c=required.map(id=>q[id]);const signature=x=>JSON.stringify({question:(x.question||'').replace(/[\d０-９,，]+/g,'#'),keys:Object.keys(x.answer?.cells||{}),sourceShape:(x.sourceData||x.tableData||[]).map?.(r=>Object.keys(r))});for(let i=0;i<c.length-1;i++)if(signature(c[i])===signature(c[i+1]))add('GATE-11','EXCESSIVE_REPETITION',required[i],required[i+1]);
 const css=read('css/style.css');if(/font-size\s*:\s*15px/.test(css))add('GATE-13','MOBILE_FONT_TOO_SMALL');
 return {findings,story:{expected:required,actual:run.visited.filter(id=>id.startsWith('C')),storyCount:run.ids.length,visitedCount:run.visited.length,premature:findings.filter(x=>x.code==='PREMATURE_STORY_TERMINATION').length,unreachable:findings.filter(x=>x.code==='UNREACHABLE_STORY_QUESTION').map(x=>x.id),loop:run.loop}};}
const mutationDetectors={FIFO_TO_MOVING_AVERAGE:s=>!s.fifo,MOVING_AVERAGE_TO_FIFO:s=>!s.moving,QUANTITY_TO_YEN:s=>s.units.quantity!=='個',LIFE_TO_YEN:s=>s.units.life!=='年',FOLIO_TO_YEN:s=>s.units.folio!==null,AMOUNT_TO_MONTH:s=>s.units.amount!=='円',PROFIT_TO_EQUITY:s=>s.classes.損益!=='closing',CASH_OVER_SHORT_TO_ASSET:s=>s.classes.現金過不足!=='temporary',RAW_INTERNAL_ID:s=>s.rawIds>0,REMOVE_FORMULA:s=>!s.explanation.formula,REMOVE_CORRECT_ACCOUNT:s=>!s.explanation.account,REMOVE_CORRECT_AMOUNT:s=>!s.explanation.amount,DUPLICATE_BS_SECTION:s=>s.bsSections!==new Set(s.bsNames).size,FONT_SIZE_15PX:s=>s.fontSize<16,STORY_ITEM_TO_EXAM_POOL:s=>s.story.some(id=>s.exam.includes(id)),NEXT_SELF_LOOP:s=>s.nextSelf,NEXT_NULL_AT_20:s=>s.reachable<25,DISPLAY_25_REACH_20:s=>s.display!==s.reachable,C004_C010_IDENTICAL:s=>new Set(s.variety).size!==s.variety.length};
function mutations(){const base={fifo:true,moving:true,units:{quantity:'個',life:'年',folio:null,amount:'円'},classes:{損益:'closing',現金過不足:'temporary'},rawIds:0,explanation:{formula:true,account:true,amount:true},bsSections:3,bsNames:['assets','liabilities','equity'],fontSize:16,story:['C004','C005','C006','C007','C008','C009','C010'],exam:[],nextSelf:false,reachable:25,display:25,variety:['4','5','6','7','8','9','10']};const cases={FIFO_TO_MOVING_AVERAGE:s=>s.fifo=false,MOVING_AVERAGE_TO_FIFO:s=>s.moving=false,QUANTITY_TO_YEN:s=>s.units.quantity='円',LIFE_TO_YEN:s=>s.units.life='円',FOLIO_TO_YEN:s=>s.units.folio='円',AMOUNT_TO_MONTH:s=>s.units.amount='か月',PROFIT_TO_EQUITY:s=>s.classes.損益='equity',CASH_OVER_SHORT_TO_ASSET:s=>s.classes.現金過不足='asset',RAW_INTERNAL_ID:s=>s.rawIds=1,REMOVE_FORMULA:s=>s.explanation.formula=false,REMOVE_CORRECT_ACCOUNT:s=>s.explanation.account=false,REMOVE_CORRECT_AMOUNT:s=>s.explanation.amount=false,DUPLICATE_BS_SECTION:s=>s.bsNames=['assets','assets','equity'],FONT_SIZE_15PX:s=>s.fontSize=15,STORY_ITEM_TO_EXAM_POOL:s=>s.exam=['C006'],NEXT_SELF_LOOP:s=>s.nextSelf=true,NEXT_NULL_AT_20:s=>s.reachable=20,DISPLAY_25_REACH_20:s=>s.reachable=20,C004_C010_IDENTICAL:s=>s.variety=Array(7).fill('same')};return Object.entries(cases).map(([name,mutate])=>{const specimen=structuredClone(base);mutate(specimen);return {name,status:mutationDetectors[name](specimen)?'KILLED':'SURVIVED'};});}
module.exports={ROOT,read,sha,json,walk,productionFiles,loadProduction,lockCheck,audit,mutations};
