'use strict';

const crypto=require('crypto'),fs=require('fs'),os=require('os'),path=require('path');
const core=require('./audit-core');
const independentOracle=require('../../independent-audit/oracles/expected-answer-oracle');
const LAYERS=['STRUCTURAL','ACCOUNTING_SEMANTIC','LEARNING','ADVERSARIAL'];
const gateContracts=[['GATE-01','semantic'],['GATE-02','user-facing'],['GATE-03','journal'],['GATE-04','ledger'],['GATE-05','trial-balance'],['GATE-06','correction'],['GATE-07','worksheet'],['GATE-08','financial-statements'],['GATE-09','comprehensive'],['GATE-10','story-progression'],['GATE-11','question-variety'],['GATE-12','ui'],['GATE-13','mobile'],['GATE-14','mutation'],['GATE-15','final-integrity']];
const findingCheck=(gate,codes)=>context=>context.auditResult.findings.filter(f=>f.gate===gate&&codes.includes(f.code));
const executableChecks={
  SEMANTIC_VALUE_UNITS:findingCheck('GATE-01',['QUANTITY_AS_YEN','LIFE_AS_YEN','FOLIO_AS_YEN','AMOUNT_AS_MONTH']),
  SEMANTIC_QUESTION_COVERAGE:findingCheck('GATE-01',['COVERAGE_TOTAL','DUPLICATE_ID','MISSING_GOLDEN']),
  USER_FACING_INTERNAL_IDS:findingCheck('GATE-02',['RAW_INTERNAL_ID']),
  USER_FACING_EXPLANATION_RELATIONS:findingCheck('GATE-02',['EXPLANATION_RELATION_INCOMPLETE']),
  JOURNAL_SPECIAL_ACCOUNT_CLASSIFICATION:findingCheck('GATE-03',['SPECIAL_ACCOUNT_MISCLASSIFIED','PROFIT_CLASSIFICATION','CASH_OVER_SHORT_CLASSIFICATION']),
  JOURNAL_HORIZONTAL_ENTRY:context=>Object.values(context.production.questions).filter(q=>q.type==='journal'&&(!Array.isArray(q.answer?.debit)||!Array.isArray(q.answer?.credit))).map(q=>({code:'JOURNAL_HORIZONTAL_ENTRY',id:q.id})),
  LEDGER_METHOD_MATCH:findingCheck('GATE-04',['FIFO_METHOD','FIFO_CONTAMINATION']),
  LEDGER_EXPECTED_CELLS:findingCheck('GATE-04',['FIXED_EXPECTED','FOLIO_EXPECTED']),
  LEDGER_UNIT_SEMANTICS:findingCheck('GATE-01',['QUANTITY_AS_YEN','LIFE_AS_YEN','FOLIO_AS_YEN','AMOUNT_AS_MONTH']),
  LEDGER_CALCULATION_TRACE:context=>questionFailures(context,'ledger',q=>answerValues(q).every(value=>mentionsValue(q.explanation,value)),'LEDGER_CALCULATION_TRACE'),
  TRIAL_BALANCE_DEBIT_TOTAL:context=>questionFailures(context,'trial_balance',q=>hasAnswerKey(q,/debit/i),'TRIAL_BALANCE_DEBIT_TOTAL'),
  TRIAL_BALANCE_CREDIT_TOTAL:context=>questionFailures(context,'trial_balance',q=>hasAnswerKey(q,/credit/i),'TRIAL_BALANCE_CREDIT_TOTAL'),
  TRIAL_BALANCE_TOTAL_EQUALITY:context=>questionFailures(context,'trial_balance',q=>trialBalanceTotals(q).debit===trialBalanceTotals(q).credit,'TRIAL_BALANCE_TOTAL_EQUALITY'),
  CORRECTION_RECORDED_EVIDENCE:context=>questionFailures(context,'correction',q=>q.materials?.some(m=>m.recorded&&m.evidence),'CORRECTION_RECORDED_EVIDENCE'),
  CORRECTION_ENTRY:context=>questionFailures(context,'correction',q=>['debitAccount','debitAmount','creditAccount','creditAmount'].every(key=>key in (q.answer?.cells||{})),'CORRECTION_ENTRY'),
  WORKSHEET_COLUMNS:context=>questionFailures(context,'worksheet',q=>['tb','adj','pl','bs'].every(prefix=>Object.keys(q.answer?.cells||{}).some(key=>key.toLowerCase().startsWith(prefix))),'WORKSHEET_COLUMNS'),
  WORKSHEET_CLASSIFICATION:context=>questionFailures(context,'worksheet',q=>/損益|P\/L/.test(q.explanation)&&/貸借|B\/S/.test(q.explanation),'WORKSHEET_CLASSIFICATION'),
  FINANCIAL_STATEMENT_VALUES:findingCheck('GATE-08',['ACCOUNTING_EQUATION']),
  FINANCIAL_STATEMENT_EQUATION:context=>questionFailures(context,'financial_statement',q=>answerValues(q).every(Number.isFinite),'FINANCIAL_STATEMENT_EQUATION'),
  COMPREHENSIVE_RELATION_TRACE:context=>questionFailures(context,'comprehensive',q=>q.materials?.length>1&&answerValues(q).every(value=>mentionsValue(q.explanation,value)),'COMPREHENSIVE_RELATION_TRACE'),
  STORY_DISPLAY_COUNT:findingCheck('GATE-10',['PROGRESS_COUNT_MISMATCH']),
  STORY_POSITION_SEQUENCE:findingCheck('GATE-10',['STORY_POSITION_GAP','PREMATURE_STORY_TERMINATION']),
  STORY_REACHABILITY:findingCheck('GATE-10',['UNREACHABLE_STORY_QUESTION','UNEXPECTED_LOOP']),
  QUESTION_VARIETY:findingCheck('GATE-11',['EXCESSIVE_REPETITION']),
  UI_BALANCE_SHEET_SECTIONS:findingCheck('GATE-12',['DUPLICATE_BS_SECTION']),
  MOBILE_MINIMUM_FONT:findingCheck('GATE-13',['MOBILE_FONT_TOO_SMALL']),
  MUTATION_ALL_KILLED:context=>context.mutationResults.filter(x=>x.status!=='KILLED'),
  MUTATION_CAUSAL_DELTA:context=>context.mutationResults.filter(x=>!x.causalDeltaConfirmed),
  ANSWER_CORRUPTION_MUTATIONS:context=>context.answerCorruptionResults.filter(x=>x.status!=='KILLED'),
  AUDIT_LOCK_INTACT:context=>context.lockResult.ok?[]:context.lockResult.errors,
  AUDIT_RUNNER_COMPLETED:context=>context.auditResult.findings.filter(f=>f.code==='RUNNER_EXCEPTION'),
  ORACLE_NO_SELF_REFERENCE:()=>oracleSelfReferenceFindings()
};

function answerValues(question){return Object.values(question.answer?.cells||{}).concat((question.answer?.debit||[]).map(x=>x.amount),(question.answer?.credit||[]).map(x=>x.amount)).filter(Number.isFinite);}
function mentionsValue(text,value){return String(text||'').includes(value.toLocaleString('ja-JP'))||String(text||'').includes(String(value));}
function questionFailures(context,type,predicate,code){return Object.values(context.production.questions).filter(q=>q.type===type&&!predicate(q)).map(q=>({code,id:q.id}));}
function hasAnswerKey(question,pattern){return Object.keys(question.answer?.cells||{}).some(key=>pattern.test(key));}
function trialBalanceTotals(question){const cells=question.answer?.cells||{},keys=Object.keys(cells);return {debit:cells[keys.find(k=>/debit/i.test(k))],credit:cells[keys.find(k=>/credit/i.test(k))]};}
function loadContracts(){return Object.fromEntries(gateContracts.map(([gate,name])=>[gate,core.json(`independent-audit/contracts/${name}.json`)]));}
function validateContract(contract){const errors=[];if(!Array.isArray(contract.requirements)||contract.requirements.length===0)errors.push('GATE_UNIMPLEMENTED');if(!Array.isArray(contract.requiredCheckIds)||contract.requiredCheckIds.length===0)errors.push('GATE_UNIMPLEMENTED');if(!Array.isArray(contract.requiredLayers)||contract.requiredLayers.length===0)errors.push('REQUIRED_LAYER_NOT_EXECUTED');if(!Array.isArray(contract.dependencies))errors.push('GATE_UNIMPLEMENTED');if(contract.passPolicy!=='all-required-checks-layers-and-dependencies-pass')errors.push('GATE_UNIMPLEMENTED');for(const requirement of contract.requirements||[])if(!requirement.requirementId||!requirement.requiredCheckId||!executableChecks[requirement.requiredCheckId])errors.push('REQUIREMENT_WITHOUT_EXECUTABLE_CHECK');for(const id of contract.requiredCheckIds||[])if(!executableChecks[id])errors.push('REQUIREMENT_WITHOUT_EXECUTABLE_CHECK');return [...new Set(errors)];}
function dependencySatisfied(dependency,report){if(!report)return false;if((dependency.acceptedStatuses||['PASS']).includes(report.status)){if(report.status!=='FAIL')return true;const actual=new Set(report.findings.filter(f=>!['DEPENDENCY_NOT_SATISFIED'].includes(f.code)).map(f=>f.code));return actual.size>0&&(dependency.expectedRedCodes||[]).length>0&&[...actual].every(code=>dependency.expectedRedCodes.includes(code));}return false;}
function evaluateContract(gate,contract,checks,auditFindings=[],priorReports={}){const required=contract.requiredCheckIds||[],executed=required.filter(id=>checks[id]),missing=required.filter(id=>!checks[id]),layers={};for(const layer of LAYERS){const layerRequired=required.filter(id=>contract.checkLayers?.[id]===layer),layerExecuted=layerRequired.filter(id=>checks[id]),passedCheckIds=layerExecuted.filter(id=>checks[id].status==='PASS'),failedCheckIds=layerExecuted.filter(id=>checks[id].status==='FAIL'),explicitNA=(contract.notApplicableLayers||[]).includes(layer);layers[layer]={requiredCheckIds:layerRequired,executedCheckIds:layerExecuted,passedCheckIds,failedCheckIds,status:explicitNA?'N/A':layerRequired.length===0||layerExecuted.length!==layerRequired.length||failedCheckIds.length?'FAIL':'PASS'};}const findings=[];if(required.length===0)findings.push({gate,code:'CHECK_COUNT_ZERO'});if(missing.length)findings.push({gate,code:'REQUIRED_CHECK_NOT_EXECUTED',detail:missing});for(const layer of contract.requiredLayers||[])if(layers[layer].executedCheckIds.length===0)findings.push({gate,code:'REQUIRED_LAYER_NOT_EXECUTED',detail:layer});for(const code of validateContract(contract))findings.push({gate,code});const dependencyEvidence=(contract.dependencies||[]).map(dependency=>({dependency,satisfied:dependencySatisfied(dependency,priorReports[dependency.gateId])}));for(const item of dependencyEvidence.filter(x=>!x.satisfied))findings.push({gate,code:'DEPENDENCY_NOT_SATISFIED',detail:item.dependency.gateId});const failed=executed.filter(id=>checks[id].status==='FAIL'),status=required.length>0&&missing.length===0&&findings.length===0&&failed.length===0&&(contract.requiredLayers||[]).every(layer=>layers[layer].status==='PASS')?'PASS':'FAIL';return {gate,status,requiredCheckIds:required,executedCheckIds:executed,passedCheckIds:executed.filter(id=>checks[id].status==='PASS'),failedCheckIds:failed,layers,dependencyEvidence,findings:[...auditFindings,...findings]};}
function executeContracts(auditResult,mutationResults,answerCorruptionResults,lockResult,production){const contracts=loadContracts(),checks={},reports={},context={auditResult,mutationResults,answerCorruptionResults,lockResult,production};for(const [gate,name] of gateContracts){const contract=contracts[gate];for(const id of contract.requiredCheckIds||[]){if(!executableChecks[id])continue;let failures,error;try{failures=executableChecks[id](context)||[];}catch(reason){failures=[{code:'CHECK_EXCEPTION'}];error=reason.message;}checks[id]={id,layer:contract.checkLayers?.[id],status:failures.length?'FAIL':'PASS',failures,error};}reports[gate]={...evaluateContract(gate,contract,checks,auditResult.findings.filter(x=>x.gate===gate),reports),contract:name};}return {reports,checks};}

const commonQuestionChecks={QUESTION_PRESENT:q=>Boolean(q),QUESTION_STRUCTURE:q=>Boolean(q&&typeof q.question==='string'&&q.answer&&typeof q.answer==='object'),QUESTION_EXPLANATION:q=>Boolean(q?.explanation?.trim()),QUESTION_TYPE_RECOGNIZED:q=>recognizedQuestionType(q)};
function recognizedQuestionType(question){return Boolean(question&&Object.hasOwn(typeQuestionChecks,question.type)&&Object.keys(typeQuestionChecks[question.type]).length);}
function worksheetSchema(question){const table=question?.table,cells=question?.answer?.cells;return {valid:Boolean(table&&Array.isArray(table.rows)&&table.rows.length&&Array.isArray(table.inputCells)&&table.inputCells.length&&cells&&typeof cells==='object'&&table.inputCells.every(key=>Object.hasOwn(cells,key)))};}
function worksheetExplanationEvidence(question){
 const text=String(question?.explanation||''),rows=question?.table?.rows||[],cells=question?.answer?.cells||{};
 const sourceLabels=rows.flatMap(row=>[row.account,row.item]).filter(value=>typeof value==='string'&&value.length>1),sourceNumbers=rows.flatMap(row=>Object.values(row).filter(Number.isFinite));
 const mentionsAny=values=>values.some(value=>mentionsValue(text,value));
 const answerNumbers=Object.values(cells).filter(Number.isFinite);
 return {source:mentionsAny(sourceLabels)&&mentionsAny(sourceNumbers.length?sourceNumbers:answerNumbers),calculation:mentionsAny(answerNumbers)&&/(?:計算|合計|差し引|[＋+－−×÷＝=]|整理|修正|振替|締切)/u.test(text),classification:/(?:損益計算書|損益|P\/L)/u.test(text)&&/(?:貸借対照表|貸借|B\/S)/u.test(text),placement:/(?:振り分け|転記|表示|配置|記入)/u.test(text)&&mentionsAny(answerNumbers)};
}
const typeQuestionChecks={
 journal:{JOURNAL_CORRECT_ACCOUNTS:q=>[...(q.answer?.debit||[]),...(q.answer?.credit||[])].every(x=>x.account&&q.explanation.includes(x.account)),JOURNAL_DEBIT_CREDIT:q=>(q.answer?.debit?.length||0)>0&&(q.answer?.credit?.length||0)>0,JOURNAL_AMOUNTS:q=>answerValues(q).length>0&&answerValues(q).every(Number.isFinite),JOURNAL_SPECIFIC_REASON:q=>/増加|減少/.test(q.explanation)&&/借方/.test(q.explanation)&&/貸方/.test(q.explanation),JOURNAL_CALCULATION:q=>answerValues(q).every(v=>mentionsValue(q.explanation,v))},
 ledger:{LEDGER_SUBTYPE:q=>Boolean(q.category&&q.table),LEDGER_CALCULATION_METHOD:q=>/残高|先入先出|移動平均|転記|計算/.test(q.question+q.explanation),LEDGER_EXPECTED_CELLS:q=>q.table.inputCells.every(key=>key in q.answer.cells),LEDGER_UNITS:q=>Object.values(q.table.inputMetadata||{}).every(meta=>meta.semanticType),LEDGER_CALCULATION_PROCESS:q=>answerValues(q).every(v=>mentionsValue(q.explanation,v))},
 trial_balance:{TRIAL_BALANCE_DEBIT:q=>hasAnswerKey(q,/debit/i),TRIAL_BALANCE_CREDIT:q=>hasAnswerKey(q,/credit/i),TRIAL_BALANCE_EXPLICIT_ADDITION:q=>/\+|加え|合計/.test(q.explanation),TRIAL_BALANCE_EQUAL:q=>trialBalanceTotals(q).debit===trialBalanceTotals(q).credit},
 correction:{CORRECTION_RECORDED:q=>q.materials?.some(m=>m.recorded),CORRECTION_EVIDENCE:q=>q.materials?.some(m=>m.evidence),CORRECTION_ENTRY:q=>['debitAccount','debitAmount','creditAccount','creditAmount'].every(key=>key in q.answer.cells)},
 worksheet:{WORKSHEET_PRE_ADJUSTMENT:q=>worksheetSchema(q).valid&&worksheetExplanationEvidence(q).source,WORKSHEET_ADJUSTMENT:q=>worksheetSchema(q).valid&&worksheetExplanationEvidence(q).calculation,WORKSHEET_POST_ADJUSTMENT:q=>worksheetSchema(q).valid&&worksheetExplanationEvidence(q).classification,WORKSHEET_PL_BS:q=>worksheetSchema(q).valid&&worksheetExplanationEvidence(q).placement},
 financial_statement:{FINANCIAL_STATEMENT_SPECIFIC_VALUES:q=>answerValues(q).every(v=>mentionsValue(q.explanation,v)),FINANCIAL_STATEMENT_FORMULA:q=>/＝|=|差し引|合計/.test(q.explanation),FINANCIAL_STATEMENT_CONSISTENCY:q=>answerValues(q).every(Number.isFinite)},
 comprehensive:{COMPREHENSIVE_CROSS_SOURCE:q=>q.materials?.length>1,COMPREHENSIVE_JUDGMENT:q=>/判断|ため|ので|先に|差|一致|等し/.test(q.explanation),COMPREHENSIVE_CALCULATION:q=>/＝|=|計算|合計/.test(q.explanation),COMPREHENSIVE_FINAL_ANSWER:q=>answerValues(q).every(v=>mentionsValue(q.explanation,v))}
};
function directAuditRecordComplete(record,question){const specific=question&&Object.hasOwn(typeQuestionChecks,question.type)?Object.keys(typeQuestionChecks[question.type]):[];return Boolean(question&&specific.length&&record&&record.questionType===question.type&&record.requiredCheckIds.includes('QUESTION_TYPE_RECOGNIZED')&&record.executedCheckIds.includes('QUESTION_TYPE_RECOGNIZED')&&record.passedCheckIds.includes('QUESTION_TYPE_RECOGNIZED')&&specific.every(id=>record.requiredCheckIds.includes(id)&&record.executedCheckIds.includes(id)&&record.passedCheckIds.includes(id))&&record.requiredCheckIds.includes('INDEPENDENT_EXPECTED_ANSWER')&&record.executedCheckIds.includes('INDEPENDENT_EXPECTED_ANSWER')&&record.passedCheckIds.includes('INDEPENDENT_EXPECTED_ANSWER')&&record.requiredCheckIds.every(id=>record.executedCheckIds.includes(id))&&record.failedCheckIds.length===0);}
function questionReview(questions){const expected=core.json('independent-audit/golden/question-ids.json').ids,raw=core.read('data/questions.js'),authored=[...raw.matchAll(/^  "([A-Z]\d{3})": \{/gmu)].map(m=>m[1]),duplicates=new Set(authored.filter((id,index)=>authored.indexOf(id)!==index));return expected.map(questionId=>{const question=questions[questionId],specific=question&&Object.hasOwn(typeQuestionChecks,question.type)?typeQuestionChecks[question.type]:{},truth=independentOracle.expectedFor(questionId),checks={...commonQuestionChecks,...specific,INDEPENDENT_EXPECTED_ANSWER:q=>Boolean(truth.expected)&&stable(q?.answer)===stable(truth.expected)},requiredCheckIds=Object.keys(checks),results=Object.entries(checks).map(([id,fn])=>({id,pass:Boolean(fn(question))&&(id!=='QUESTION_PRESENT'||!duplicates.has(questionId))})),executedCheckIds=results.map(x=>x.id),passedCheckIds=results.filter(x=>x.pass).map(x=>x.id),failedCheckIds=results.filter(x=>!x.pass).map(x=>x.id),sourceHash=question?crypto.createHash('sha256').update(JSON.stringify(question)).digest('hex'):null,record={questionId,questionType:question?.type??null,requiredCheckIds,executedCheckIds,passedCheckIds,failedCheckIds,sourceHash,independentExpectedSourceHash:truth.sourceHash};return {...record,status:directAuditRecordComplete(record,question)?'PASS':'FAIL'};});}
function DIRECT_AUDIT_ALL_PASS(records,questions){return records.length>0&&records.every(record=>directAuditRecordComplete(record,questions[record.questionId]));}
function summarizeQuestions(records,questions){const expectedIds=core.json('independent-audit/golden/question-ids.json').ids,expected=new Set(expectedIds),reviewed=new Set(records.map(x=>x.questionId)),actual=Object.keys(questions),independentlyChecked=records.filter(x=>x.executedCheckIds.includes('INDEPENDENT_EXPECTED_ANSWER')&&x.passedCheckIds.includes('INDEPENDENT_EXPECTED_ANSWER')).length,directlyTested=records.filter(record=>directAuditRecordComplete(record,questions[record.questionId])).length;return {TOTAL:expectedIds.length,DIRECTLY_TESTED:directlyTested,INDEPENDENT_EXPECTED_CHECKED:independentlyChecked,PASS:DIRECT_AUDIT_ALL_PASS(records,questions)?records.length:directlyTested,FAIL:records.length-directlyTested,MISSING:expectedIds.filter(id=>!reviewed.has(id)||!records.find(x=>x.questionId===id)?.sourceHash).length,DUPLICATE:actual.length-new Set(actual).size+actual.filter(id=>!expected.has(id)).length};}
function stable(value){return JSON.stringify(value);}
function oracleSelfReferenceFindings(){const files=core.walk('independent-audit/oracles').filter(file=>/\.(?:js|json)$/u.test(file)),forbidden=/\bquestion\s*\.\s*(?:answer|explanation)\b|\bitem\s*\.\s*(?:answer|explanation)\b/u;return files.filter(file=>forbidden.test(core.read(file))).map(file=>({code:'ORACLE_SELF_REFERENCE',file}));}
function answerCorruptionMutations(){const temporaryRoot=fs.mkdtempSync(path.join(os.tmpdir(),'boki-answer-corruption-'));try{for(const file of core.productionFiles()){const destination=path.join(temporaryRoot,file);fs.mkdirSync(path.dirname(destination),{recursive:true});fs.copyFileSync(path.join(core.ROOT,file),destination);}const original=core.loadProduction(temporaryRoot).questions,cases=[['JOURNAL_ACCOUNT','J001',q=>{q.answer.debit[0].account='誤科目';}],['JOURNAL_AMOUNT','J001',q=>{q.answer.debit[0].amount+=1;}],['JOURNAL_ANSWER_EXPLANATION','J001',q=>{q.answer.debit[0].account='誤科目';q.explanation=q.explanation.replaceAll('現金','誤科目');}],['LEDGER_CELL','L001',q=>{q.answer.cells.r2_balance+=1;}],['TRIAL_BALANCE_BOTH_TOTALS','T001',q=>{q.answer.cells.total_debit+=1;q.answer.cells.total_credit+=1;}],['CORRECTION_BOTH_SIDES','E001',q=>{q.answer.cells.debitAccount='誤科目A';q.answer.cells.creditAccount='誤科目B';}],['WORKSHEET_VALUE','D001',q=>{const key=Object.keys(q.answer.cells).find(k=>Number.isFinite(q.answer.cells[k]));q.answer.cells[key]+=1;}],['FINANCIAL_STATEMENT_VALUE','F001',q=>{q.answer.cells.netIncome+=1;}],['COMPREHENSIVE_VALUE','C001',q=>{q.answer.cells.netIncome+=1;}]];return cases.map(([mutationId,questionId,mutate])=>{const questions=structuredClone(original);mutate(questions[questionId]);const row=questionReview(questions).find(x=>x.questionId===questionId),killed=row.failedCheckIds.includes('INDEPENDENT_EXPECTED_ANSWER');return {mutationId,questionId,expectedFailureCode:'INDEPENDENT_EXPECTED_ANSWER',actualFailureCode:killed?'INDEPENDENT_EXPECTED_ANSWER':null,status:killed?'KILLED':'SURVIVED'};});}finally{fs.rmSync(temporaryRoot,{recursive:true,force:true});}}
module.exports={LAYERS,gateContracts,executableChecks,loadContracts,validateContract,dependencySatisfied,evaluateContract,executeContracts,typeQuestionChecks,worksheetSchema,worksheetExplanationEvidence,directAuditRecordComplete,DIRECT_AUDIT_ALL_PASS,questionReview,summarizeQuestions,oracleSelfReferenceFindings,answerCorruptionMutations};
