'use strict';
const assert = require('assert');
const fs = require('fs');

const harness = fs.readFileSync('.github/visual/harness.html','utf8');
const runner = fs.readFileSync('.github/visual/run-visual.js','utf8');
const order = ['data/accounting-domain.js','data/questions.js','js/view.js','js/controller.js'].map(source => harness.indexOf(`src="/${source}"`));
assert(order.every(position => position >= 0),'harness loads every required production dependency');
assert.deepStrictEqual(order,[...order].sort((left,right) => left-right),'production dependencies load in deterministic order');
for (const dependency of ['QuestionData','AccountingDomain','AppView','AppController','AppController.accountChoices']) assert(harness.includes(dependency),`${dependency} has an explicit dependency check`);
for (const representative of ['fixed-asset','inventory','ledger','journal','worksheet','journal-book','notes-register','general-ledger','inventory-ledger','voucher']) assert(harness.includes(representative),`${representative} has a canonical selector`);
assert(harness.includes('HARNESS_DEPENDENCY_MISSING:'),'missing dependencies fail with the stable diagnostic');
assert(harness.includes("question.answer?.cells?.[cellId]"), 'editable canonical answers participate in intrinsic width measurement');
assert(harness.includes('representativeColumn(key)') && harness.includes('representativeQuestion = question'), 'browser sizing uses the exact rendered representative');
assert(harness.includes('representativeColumnKey(key)') && harness.includes('cellId === key'), 'column fallback can resolve a representative cell ID to its table column');
assert(harness.includes('representativeControl(key)') && harness.includes('Object.prototype.hasOwnProperty.call(cells,key)') && harness.includes("answerSource:'cell'"), 'card controls prefer the exact answer cell before column fallback');
assert(harness.includes('visibleValues') && harness.includes('editableAnswers'), 'representative visible and editable evidence remain separately diagnosable');
assert(harness.includes('requiredInputCharacters'), 'representative profiles expose exact-column input character requirements');
assert(runner.includes('VISUAL_HARNESS_MISSING_ELEMENT:${measuredCase}:${questionId}:${name}'), 'missing required DOM reports case, question, and element');
assert(runner.includes("const isJournal = measuredCase === 'journal'"), 'journal measurement has an explicit case branch');
assert(runner.includes("requireElement(document.querySelector(isJournal ? '#journal-container .journal-row' : '.answer-table'), 'table')"), 'table or journal surface is required explicitly');
assert(runner.includes("requireElement(document.querySelector(isJournal ? '#journal-container .journal-grid-scroll' : '#table-container'), 'wrapper')"), 'journal measurement uses the inner grid scroller while other cases use the table container');
assert(!runner.includes("isJournal ? '#journal-container' : '#table-container'"), 'journal measurement cannot regress to the outer instruction container');
const tableGuard = runner.indexOf("const table = requireElement"), wrapperGuard = runner.indexOf("const wrapper = requireElement", tableGuard);
assert(tableGuard >= 0 && wrapperGuard > tableGuard && runner.indexOf('getComputedStyle(table)',wrapperGuard) > wrapperGuard, 'table style access occurs only after required-element guards');
assert(runner.includes('stickyLeft:') && runner.includes('stickyViewportLeft:') && runner.includes('contextWidth:') && runner.includes('viewportWidth:'), 'sticky metrics remain collected after guard repair');
assert(runner.includes('naturalViewportLefts') && runner.includes('naturalViewportLeft:'), 'sticky metrics preserve each column natural position before scrolling');
assert(runner.includes("isJournal ? [...wrapper.querySelectorAll('.journal-row')] : [...(table.tBodies?.[0]?.rows || [])]"), 'journal rows never use HTMLTableElement body collections');
assert(runner.includes("isJournal ? wrapper.querySelector('.journal-header') : table.tHead?.rows?.[0]"), 'journal headers never use HTMLTableElement head collections');
assert(!runner.includes('table?.tBodies[0]') && !runner.includes('table?.tHead?.rows[0]'), 'unsafe optional chaining cannot index an undefined table collection');
assert(runner.includes('journalRowHeight:') && runner.includes('hasEditableControl:'), 'journal-specific row and control metrics remain reported');
for (const property of ['fontFamily','fontSize','fontWeight','fontStyle','fontStretch','fontVariant','letterSpacing','fontKerning','fontFeatureSettings']) assert(runner.includes(`'${property}'`), `measurement probes copy computed ${property}`);
assert(!runner.includes('font:style.font'), 'measurement probes do not use lossy font shorthand');
assert(runner.includes('headerFont:{ actual:headerMeasurement.actualFont,probe:headerMeasurement.probeFont }'), 'actual and probe header fonts remain independently diagnosable');
assert(runner.includes('headerHorizontalChrome,cellHorizontalChrome,inputChrome,inputInnerWidth,requiredHeaderWidth,requiredCellWidth'), 'header, cell, and input chrome plus semantic requirements remain separate');
assert(runner.includes('editableAnswerWidth > inputInnerWidth + 0.5'), 'editable fit compares text against the actual input inner width with browser tolerance');
const cardStart = runner.indexOf('if (cardRoot) {'), cardEnd = runner.indexOf('const table = requireElement', cardStart);
const cardBranch = runner.slice(cardStart, cardEnd);
assert(runner.includes("const cardRoot = document.querySelector(measuredCase === 'fixed-asset' ? '.fixed-asset-ledger' : '.bookkeeping-form');"), 'the expected-answer card path covers both fixed-asset and bookkeeping cards');
assert(cardBranch.includes('window.visualHarness.representativeControl(key)') && cardBranch.includes('requiredTextWidth(control, editableAnswers)'), 'card controls measure the exact expected answer using the rendered control font');
assert(cardBranch.includes('editableAnswerWidth > inputInnerWidth + 0.5'), 'card expected-answer width is compared with usable input inner width');
assert(cardBranch.includes('answerSource:representative?.answerSource || null') && cardBranch.includes('editableAnswerWidth,inputPadding,inputChrome,inputInnerWidth') && cardBranch.includes('editableFont:'), 'card visual evidence preserves answer source, expected-width, usable-width, chrome, and font diagnostics');
assert(!cardBranch.includes('control.scrollWidth > control.clientWidth'), 'card fit cannot regress to measuring an empty control scroll box');
console.log('visual harness source checks: dependencies, order, diagnostics, representatives: ok');
